name: clean_todo_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  bcrypt: ^1.2.0
  change_case: ^2.2.0
  dart_frog_auth: ^1.2.2
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  equatable: ^2.0.8
  fpdart: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mailer: ^6.6.0
  mongo_dart: ^0.10.5
  password_generator: ^1.0.0
  postgres: ^3.5.9
  string_validator: ^1.2.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_lint: ^0.1.0
  json_serializable: ^6.11.3
  mocktail: ^1.0.3
  test: ^1.25.5
